### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by ScMofeoluwa** [FlashPayInc/flashpay-core#21]
# Abstract
We'd love to have endpoints that help create and verify transactions

# Motivation
WAGMI🚀

# Specification
- Create two new endpoints in `apps/payments/views.py`
- You can call them `CreateTransactionView` and `VerifyTransactionView`

- [x] The `CreateTransactionView` should accept a payment link uid and return a transaction reference.
- [x] The `VerifyTransactionView` should accept an algorand transaction hash and verify if that transaction was made to the payment link.
- [x]  Write tests. Follow format of `tests/test_views.py`.

**Comment by prettyirrelevant** [comment]
#23 closes this.
